initial DELETE stock route [SB-1]
Codubee/StockPickerTTH12-1-Back pull request #11
Opened 2021-08-04 21:34 UTC by SameedB

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
New Feature to the program

* **What is the current behavior?What does the code do before you made the new changes?** 
No delete option 

* **What is the new behavior?**
allows for users to delete a stock added to the DB using a userId and stockId

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
no, should be running normally

* **Other information**:

2021-08-05 19:29 UTC, arsoljon requested changes
Github doesn't let me select the lines for the code I want to comment on because the most recent commit includes merging main into this branch. 

Line 35, the url could be shortened to exclude '/stocks'. 
Line 36 and 37 use the params method incorrectly but in the case of this delete function, I think it would be best to use the .query method. I did some reading and found a link explaining why. https://coursework.vschool.io/express-params-and-query/

2021-08-06 06:50 UTC, jorgecan101 approved these changes, later dismissed
Looks good to me

2021-08-06 16:03 UTC, arsoljon commented on index.js
> +    const { userId } = postmanRequest.query.userId
When I ran a test, line 36 and 37 returned empty when I printed them and I received a "{ msg: 'User not found' }" when successfully running the delete request. I don't think the variables are working with braces around them. Consider removing.

2021-08-06 16:04 UTC, arsoljon reviewed
Everything is looking good. 1 more change is needed.

2021-08-08 21:24 UTC, arsoljon approved these changes
Looks good to me!

2021-08-08 22:24 UTC, jorgecan101 approved these changes
LGTM

2021-08-08 22:30 UTC, merged