Jc example
Codubee/StockPickerTTH12-1-Back pull request #2
Opened 2021-07-23 20:26 UTC by jorgecan101

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Creates the routes for /addPerson, /getAllPeople, and /deletePerson

* **What is the current behavior?What does the code do before you made the new changes?** 
The code allows for API calls to be made (via postman, curl, etc) to call routes to add people to the database, remove a person from the database, or to display all people from the database.

* **What is the new behavior?**
People can now make calls to this api, and access data from it.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
There should not be any sort of breaking changes that are introduced here. 

* **Other information**:

2021-07-26 08:03 UTC, arsoljon approved these changes, later dismissed
Works great. Looks great. Possibly refactor by cleaning up the comments and variables.

2021-07-26 08:03 UTC, arsoljon commented on JC/index.js
> +    axios.delete('https://java-sample-api-2020.herokuapp.com/deletePerson?id=' + postmanReq.query.id)
Possible refactoring chance would be to remove the test comments and move the 'route + id' into its own variable for eaiser readability.

2021-07-27 17:34 UTC, Codubee commented on JC/index.js
> +    //we are calling http://java-sample-api-2020.herokuapp.com/addPerson
I dont think this comment is necessary

2021-07-27 17:35 UTC, Codubee commented on JC/index.js
> +    //we are calling http://java-sample-api-2020.herokuapp.com/getAllPeople
I dont think this comment is necessary

2021-07-27 17:35 UTC, Codubee commented on JC/index.js
> +    //catch for errors should be working
I dont think this comment is necessary

2021-07-27 17:36 UTC, Codubee commented on JC/index.js
> +    //this is the URL needed https://java-sample-api-2020.herokuapp.com/deletePerson?id=1
I dont think this comment is necessary

2021-07-27 17:36 UTC, Codubee commented on JC/index.js
> +    userQuery = postmanReq.query.id
can you give this variable a type (var,let,const)

2021-07-27 17:37 UTC, Codubee requested changes
left some comments

2021-07-27 18:03 UTC, jorgecan101 reviewed
Made appropriate changes to the PR

2021-07-29 17:20 UTC, Codubee approved these changes
LGTM!

2021-07-29 17:24 UTC, arsoljon commented
Looks good

2021-07-29 17:25 UTC, arsoljon approved these changes
Looks good

2021-07-29 17:27 UTC, merged