Added JM Folder
Codubee/StockPickerTTH12-1-Back pull request #3
Opened 2021-07-24 04:02 UTC by jm220

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

* **What is the current behavior?What does the code do before you made the new changes?** 

* **What is the new behavior?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

* **Other information**:

2021-07-26 08:12 UTC, arsoljon approved these changes, later dismissed
Works and looks amazingly.

2021-07-26 08:12 UTC, arsoljon commented on JM/index.js
> +    .then(function(response){
Possible refactoring would be to move the 'route + id' into a separate variable to improve readability.

2021-07-27 17:22 UTC, Codubee commented on JM/index.js
> +    })
can you add an error handler here

2021-07-27 17:25 UTC, Codubee commented
Please fill out the PR template

2021-07-27 17:32 UTC, Codubee commented on JM/index.js
> +    data = axios.get(url)
I think that the data variable here would be equal to a promise. Id recommend looking at and understanding the [example get route](https://github.com/Codubee/Node-Js-API-Examples/blob/axios-examples/index.js)

2021-07-27 17:33 UTC, Codubee requested changes
Left some comments

2021-07-28 20:28 UTC, jm220 reviewed
Made changes

2021-07-29 17:14 UTC, Codubee commented on JM/index.js
> +    data = axios.get(url)
I believe that this is still incorrect Jaime. Lets setup some time so I can explain what is going on

2021-08-02 07:49 UTC, arsoljon approved these changes, later dismissed
Left 1 comment, code looks good.

2021-08-02 07:49 UTC, arsoljon commented on JM/index.js
>              const data = response.data
Everything looks good to me. Line 22 has an unused variable 'data'. Consider removing or using.

2021-08-02 16:28 UTC, arsoljon approved these changes
Looks good to me.

2021-08-03 17:06 UTC, Codubee approved these changes
LGTM!

2021-08-03 17:06 UTC, merged