JM GetRoute Weather [JM-1]
Codubee/StockPickerTTH12-1-Back pull request #9
Opened 2021-08-03 14:24 UTC by jm220

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
edited main index.js by adding GET route

* **What is the current behavior?What does the code do before you made the new changes?***
Current behavior has no GET/POST routes to main branch

* **What is the new behavior?**
Displays the current weather

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
N/A

* **Other information**:
Displays weather in Degrees F

2021-08-03 17:50 UTC, Codubee requested changes
LGTM! Just one change.

2021-08-03 17:50 UTC, Codubee commented on index.js
> +            res.status(200).json({"Temperature is: ": response.data + " F"})
Can the message here just be "temp":"76". The key "Temperature is:" is a bit of an odd key to have.

2021-08-03 18:04 UTC, arsoljon reviewed
One changed need on line 15.

2021-08-03 18:04 UTC, arsoljon commented on index.js
> +            postmanresponse.json({"Error": "Couldn't load weather"})
on line 15, I am assuming 'postmanresponse' should be 'res' because 'postmanresponse' was never initialized.

2021-08-03 18:46 UTC, arsoljon reviewed
Line 11, adjust the key.

2021-08-03 18:46 UTC, arsoljon commented on index.js
> +            res.status(200).json({"Temp: ": response.data})
You don't need the colon included in the key. Only the one in the middle, separating the key and value.

2021-08-03 20:01 UTC, arsoljon approved these changes, later dismissed
Looks good.

2021-08-04 17:27 UTC, Codubee submitted a review, later dismissed

2021-08-04 17:28 UTC, merged